version: '2'
services:
  ipsec:
    cap_add:
    - NET_ADMIN
    image: rancher/net:v0.6.0
    network_mode: ipsec
    ports:
    - 500:500/udp
    - 4500:4500/udp
    labels:
      io.rancher.sidekicks: cni-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.ipsec: 'true'
  cni-driver:
    privileged: true
    image: rancher/net:v0.6.0
    command: sh -c "touch /var/log/rancher-ipam.log && exec tail ---disable-inotify -F /var/log/rancher-ipam.log"
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'rancher-bridge'
      io.rancher.container.dns: 'true'
